version: '3.8'

services:
  backend:
    build: ./backend
    container_name: restaurante-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/database.sqlite:/app/database.sqlite
    environment:
      - NODE_ENV=development
    command: npm start
    restart: always

  app-frontend:
    build: ./app-frontend
    container_name: restaurante-web
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
