version: '3.8'

services:
  backend:
    build: ./backend
    container_name: restaurante-dona-bia
    ports:
      - "3000:3000"
    volumes:
      - ./backend/restaurante.sqlite:/app/restaurante.sqlite
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm start
    restart: always

  app-frontend:
    build: ./app-frontend
    container_name: restaurante-app
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
